site_name: Python Crash Course
repo_url: https://github.com/mciwing/mciwing.github.io
site_url: https://mydomain.org/mysite
theme:
  name: material
  logo: https://avatars.githubusercontent.com/u/153168920?s=200&v=4
  palette:
    scheme: slate
    primary: teal
    accent: amber
  icon:
    repo: fontawesome/brands/git-alt

  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - content.code.copy
    - navigation.footer
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/mciwing
copyright: 2024 MCI Wing
nav:
  - Home: index.md
  - Basics: basics.md
  - Packaging: packaging.md
plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
  - git-committers:
      repository: mciwing/mciwing.github.io
      branch: main
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences